### ISSUE TITLE
Typescript setup is more difficult than it has to be

### ISSUE THREAD

**Issue by NicholasBoll** [testing-library/cypress-testing-library#102]
Problem description:
If a project is set up to use Typescript with Cypress, an additional step is required for Typescript to understand the custom commands. The Readme shows the additional step required to be added to the `tsconfig.json`.

This is because the DefinitelyTyped package is defining type definitions for the module `@testing-library/cypress`, but to add commands at runtime, you must import `@testing-library/cypress/add-commands` which does not have a type definition associated.

Suggested solution:
2 solutions:

1. Add commands to Cypress when the developer adds `import @testing-library/cypress`
2. Update type definitions to include the `add-cypress` path.

The 2nd solution doesn't involve this repository and would not be a risk of a breaking change (other than possibly removing the line about the additional setup).

**Comment by kentcdodds** [comment]
Hmmm... I thought that I had verified that there were no additional steps necessary to get TypeScript autocomplete working other than installing the package. But maybe I was mistaken.

Between the two options you propose, I like the 2nd the best. Would you be willing to open a PR and link to it here? Thanks!

**Comment by NicholasBoll** [comment]
I think option 2 is the best as well. I'll open a PR on DefinitelyTyped

**Comment by NicholasBoll** [comment]
Pr: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41987

**Comment by NicholasBoll** [comment]
Merged, but not yet released: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41987

**Comment by kentcdodds** [comment]
Looks like this was published so we should be good now. Thank you so much @NicholasBoll!

**Comment by NicholasBoll** [comment]
Confirmed!
