### ISSUE TITLE
findAllByTestId failing on versions > 5.0.2

### ISSUE THREAD

**Issue by JoeEarly** [testing-library/cypress-testing-library#107]
- `DOM Testing Library` version: 5.1.1
- `node` version: 11.4.0
- `npm` (or `yarn`) version: npm: 6.13.1 yarn: 1.21.1

### Relevant code or config:

```js
cy.visit("/admin")
      .withConfig({})
      //.findAllByTestId("Get Started with the Building Directory app")
      .findAllByTestId("onboard-title-0")
      .should("be.visible")
      .and("contain", "Get Started")
```

### What you did:

I am creating a set of tests here and few weeks ago this was passing fine. Now with an upgrade in package version, the 'findAllByTestId' is failing. 

I rolled back versions of the cypress-testing-library so it seems this has been introduced as of Vr 5.1.1 

### What happened:
<img width="1678" alt="Screenshot 2020-01-30 at 12 01 59" src="https://user-images.githubusercontent.com/5208459/73449466-229cae80-435b-11ea-9291-8fb983983ddc.png">
<img width="557" alt="Screenshot 2020-01-30 at 12 02 07" src="https://user-images.githubusercontent.com/5208459/73449467-23354500-435b-11ea-90f3-6f7fb71b710d.png">

**Comment by kentcdodds** [comment]
Hello @JoeEarly,

Thanks for this issue. I'm sorry, I didn't notice this until I saw #109. They are the same issue. I hope you don't mind me closing this one in favor of #109 because I've already started a discussion over there. Please weigh in on ideas if you have any. Thank you!
