### ISSUE TITLE
TypeError: container.querySelectorAll is not a function

### ISSUE THREAD

**Issue by intelligentspark** [testing-library/cypress-testing-library#109]
- `cypress-testing-library` version: 5.1.1
- `node` version: 12.4.0
- `npm` (or `yarn`) version: 1.21.1 (yarn)

Relevant code or config

```javascript

describe('anonymous calculator', () => {
  it('can make calculations', () => {
    cy.visit('/')
      .findByText(/^1$/)
      .click()
      .findByText(/^\+$/)
      .click()
      .findByText(/^2$/)
      .click()
      .findByText(/^=$/)
      .click()
      .findByTestId('total')
      .should('have.text', '3')
  })
})

```

What you did: Attempted to run tjs/cypress-04 branch of [https://github.com/kentcdodds/jest-cypress-react-babel-webpack/tree/tjs/cypress-04](https://github.com/kentcdodds/jest-cypress-react-babel-webpack/tree/tjs/cypress-04)

What happened:

<img width="1201" alt="Screen Shot 2020-01-30 at 1 52 55 PM" src="https://user-images.githubusercontent.com/1282252/73480445-e459bc00-4367-11ea-95e3-9cb223e17160.png">

Reproduction repository:
[https://github.com/kentcdodds/jest-cypress-react-babel-webpack/tree/tjs/cypress-04](https://github.com/kentcdodds/jest-cypress-react-babel-webpack/tree/tjs/cypress-04)

Problem description:

TypeError: container.querySelectorAll is not a function

Suggested solution:

--

**Comment by kentcdodds** [comment]
I think this is the same issue that was brought up here: https://github.com/testing-library/cypress-testing-library/pull/100#issuecomment-580095440

Thank you for opening it so we can discuss this. cc @tlrobinson and @twgraham.

When I merged that other PR I didn't realize it was going to break this use case. I personally like this style quite a bit and would like it very much if we could get the benefits that #100 was going for without losing the ability to write tests in this way.

If we cannot, then I think we should revert #100. Anyone have ideas?

**Comment by kentcdodds** [comment]
I'd also love feedback from @NicholasBoll on this as well.

**Comment by intelligentspark** [comment]
Thanks for the quick response on this @kentcdodds!

**Comment by kentcdodds** [comment]
Just to be clear, the justification for the style I prefer is based on how `get` works:

```javascript
describe('anonymous calculator', () => {
  it('can make calculations', () => {
    cy.visit('/')
      .get('.one')
      .click()
      .get('.plus')
      .click()
      .get('.two')
      .click()
      .get('.equals')
      .click()
      .get('.total')
      .should('have.text', '3')
  })
})
```

I really like that style and want to make sure we preserve that style for our queries. I think that is least surprising for people.

**Comment by tlrobinson** [comment]
However, this isn't how `contains` works, which I'd argue is more similar to the `testing-library` commands.

The way Cypress recommends "reseting" to the root element is with `end()`: https://docs.cypress.io/api/commands/end.html#Examples

**Comment by twgraham** [comment]
@kentcdodds I think the comment i made in #100 would only apply to 5.1.0, this is 5.0.2 so it could be a different issue? 🤷‍♂️

**Comment by kentcdodds** [comment]
Oh, that's true. Maybe it is a different issue. Anyone want to dig in and figure out where the problem lies?

**Comment by twgraham** [comment]
Scratch that... It could be resolving the next minor version (5.1.0) because the package.json requires ^5.0.2. Probably the same issue 😅

**Comment by intelligentspark** [comment]
Oh, Crumbs.  No, I was on 5.1.x, I'm sorry @kentcdodds @twgraham!

**Comment by twgraham** [comment]
> When I merged that other PR I didn't realize it was going to break this use case. I personally like this style quite a bit and would like it very much if we could get the benefits that #100 was going for without losing the ability to write tests in this way.

Your call - I can see the benefits of sticking to the old way, and the new way which @tlrobinson has provided. I don't think you can have it both ways though (from a usability perspective). It would become confusing (magic?) how the command resolves elements. I would also suggest that adding it as an option is a bad idea e.g. findByText(..., { usePrevious: true })

Pick a method and stick with it 👍

**Comment by kentcdodds** [comment]
Ok, I think that in order to address the breaking change I'm going to revert #100 right now, and then we can talk about the merits of making a breaking change to support it in a new major version bump.

**Comment by kentcdodds** [comment]
5.1.2 has been published to revert that change. I apologize for not recognizing the implications of the change in the first place. Sorry for the bump.

**Comment by kentcdodds** [comment]
I've opened a new issue to discuss adding #100 as a breaking change.

Please comment if you have opinions: #110

**Comment by NicholasBoll** [comment]
I'll look up this issue and see if it is related to #100 and if there is any way to introduce #100 as a non-breaking change

**Comment by ayush000** [comment]
For people who came across this issue, from what I understand, starting from `@testing-library/cypress@6.0.0`, they are no longer supporting chaining of multiple `find*` commands. So, you'll have to write it as

```js
    cy.visit('/')
    cy.findByText(/^1$/).click()
    cy.findByText(/^\+$/).click()
    cy.findByText(/^2$/).click()
    cy.findByText(/^=$/).click()
    cy.findByTestId('total').should('have.text', '3')
```
More discussion about this decision on: https://github.com/testing-library/cypress-testing-library/issues/110

@kentcdodds @tlrobinson please correct me if I'm wrong. Also, it would be helpful to add this change to release changelog: https://github.com/testing-library/cypress-testing-library/releases.

**Comment by kentcdodds** [comment]
Hi @ayush000,

It was included 😁

![Screenshot_20200404-144059](https://user-images.githubusercontent.com/1500684/78460933-6a54f480-7682-11ea-8fec-22849ba0abc6.png)

**Comment by ayush000** [comment]
ahh! Missed it.

**Comment by gusaiani** [comment]
Hi all, regarding https://testingjavascript.com/lessons/cypress-installing-cypress-testing-library,

I tried to not add `data-testid` to markup that would be sent to prod, so ended up writing it this way:

```
    cy.visit('/')
    cy.findByText(/^1$/).click()
    cy.findByText(/^\+$/).click()
    cy.findByText(/^2$/).click()
    cy.findByText(/^=$/).click()
    cy.findAllByText(/^3$/).should('have.length', 2)
```

or we could sacrifice smallest addends and have no ambiguity, for example

```
    cy.findByText(/^5$/).click()
    cy.findByText(/^\+$/).click()
    cy.findByText(/^6$/).click()
    cy.findByText(/^=$/).click()
    cy.findByText(/^11$/).should('be.visible')
```

I'm currently learning from the course in real time (wonderful course btw), so if there are better ways, please @ me 👋

**Comment by kentcdodds** [comment]
I agree that would be better for the course. Will probably do something like that in the next update 👍 thanks!
