### ISSUE TITLE
Add autocomplete support for the should(chainer, ...) variants

### ISSUE THREAD

**Issue by tormodhau** [testing-library/cypress-testing-library#131]
**Environment:**

- `cypress-testing-library` version: 5.3.0
- `node` version: 12.13.1
- `npm` (or `yarn`) version: 6.12.1
- `typescript` version: 3.7.4
- `Intellij Ultimate` version: 2019.3.3 

**Relevant code or config:**

```json
  // ts.config
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "@types/testing-library__cypress"],
    "noEmit": false
  },
```

```javascript
// support/index.ts
import "@testing-library/cypress/add-commands";
```

**What you did:**

```javascript
cy.findAllByText('"Some text').should('have.length', 2);
```

**What happened:**

![image](https://user-images.githubusercontent.com/4433808/76624999-a343f280-6536-11ea-92d2-5bba493225c6.png)

You get a warning and no autocompletion. The code runs just fine.

**Problem description:**

When using the `cy.get().should()`-syntax in Cypress, you get autocompletion for all the "chainer" variants (as in `should("chainer")`). Using e.g `cy.findByText().should()` from CTL will not only give you a linter warning, but also no autocompletion. 

**Suggested solution:**

If there is an existing solution to this issue, please add it to the readme. Alternatively: perhaps it would be possible to add the Typescript definitions for each `should`-variant as they have done for the original `cy.get().should()`-variants?

**Comment by kentcdodds** [comment]
I think this is resolved in the latest version.
