### ISSUE TITLE
cy.findByText always returns true with should('not.exist')

### ISSUE THREAD

**Issue by coryhouse** [testing-library/cypress-testing-library#135]
- `cypress-testing-library` version:  6.0
- `node` version: 12.13.1
- `npm` (or `yarn`) version: 6.13

Relevant code or config

```javascript
cy.findByText('Non-existing Button Text').should('not.exist')
```

What you did:
Tried writing a test to assert non-existence. It always passes, even when the text exists.

What happened:

Reproduction repository:

https://github.com/coryhouse/cy-doesnt-exist-bug

To run:
```
npm install
npm run cy
```

Problem description:

This always passes, even when the text exists:
```js
cy.findByText('Non-existing Button Text').should('not.exist')
```

Suggested solution:

Looks like cy.contains works fine for this use case, but would be great if the documented approach could work.

**Comment by pranjaljately** [comment]
Hi @coryhouse,

Looking at your repo I noticed you were doing the following:
` cy.findByText('save to reload.').should('not.exist');`

**Using strings does a full string match,** which would explain why the test was passing.

 To do a **substring** match you should do the following: 
` cy.findByText(/save to reload./).should('not.exist');`

You can also see more examples [here](https://testing-library.com/docs/dom-testing-library/api-queries#textmatch-examples).

Hope that helps 😀👍 

Thanks,
Pranjal

**Comment by kentcdodds** [comment]
Thanks @pranjaljately!
