### ISSUE TITLE
[solved] I get an error message if I don't prepend calls to findBy... with a get('body') call

### ISSUE THREAD

**Issue by dutzi** [testing-library/cypress-testing-library#142]
- `cypress-testing-library` version: ^6.0.0
- `node` version: v10.21.0
- `npm` (or `yarn`) version: 1.22.4 (yarn)

Relevant code or config

```javascript
    cy.visit('/email-verified')
      .findByText(/okay/i)
```

What you did:

I visit a page and call `findByText`

What happened:

I get the following error message:

```
Timed out retrying: Expected container to be an Element, a Document or a DocumentFragment but got Window.
```

![image](https://user-images.githubusercontent.com/927310/85422683-88920880-b57e-11ea-8341-80082ee4fdf7.png)

If I call `get('body')` before calling `findByText` it works:

```js
    cy.visit('/email-verified')
      .get('body')
      .findByText(/okay/i)
```

**Comment by dutzi** [comment]
Just posted this for anyone encoutering this. Turns out cypress-testing-library no longer supports chaining commands, so you have to write something like:

```js
cy.visit('/page');
cy.findByText(/okay/i).click();
cy.findByText(/another button/i).click()
```

**Comment by selbekk** [comment]
This sounds like a bug?

**Comment by kentcdodds** [comment]
Hmmm... cc @NicholasBoll?

**Comment by selbekk** [comment]
Oh sorry, it’s just a new API - you’re not supposed to chain stuff any more. Perhaps we could implement a better error message?

**Comment by NicholasBoll** [comment]
@dutzi It isn't true that Cypress Testing Library no longer supports chaining. It now supports _scoping_. All Cypress Testing Library queries are called Dual Commands: https://docs.cypress.io/api/cypress-api/custom-commands.html#Dual-Commands.

Previously they were Parent Commands: https://docs.cypress.io/api/cypress-api/custom-commands.html#Parent-Commands

The difference is if a query _starts_ a chain, it will assume a global context (find from the root of the document). If you have a previous subject, it will start there.

Before it wasn't possible to scope any `find*` queries. Now you can. I've had conversations with the core Cypress team and they recommend starting a new chain when using Parent commands like `cy.get`. I couldn't find specific recommendation against the pattern of chaining `.get` from a previous chain, but none of the documentation chains a `.get`.

I like to think of a "chain" like I think of a sentence. There is a primary subject and something acting on that subject - either an action (like `click`) or an assertion (like `should`). Subjects can be narrowed (like adjectives to help describe the subject) and related actions can be grouped. You might say something like "We went to the fair and enjoyed ourselves". That's a compound sentence with a related subject. Where did you enjoy yourselves? At the fair. Who enjoyed themselves? We did. The same is true for Cypress command chains. It is easier to understand when related groups of commands are part of a chain. A 20+ chain of commands doesn't have any central theme or breaking point. Everything runs together like a run-on sentence without structure.

More info on subject management: https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Subject-Management

Change was here: https://github.com/testing-library/cypress-testing-library/pull/130

**Comment by kentcdodds** [comment]
Very well said. Thanks @NicholasBoll 👍👍👏
