### ISSUE TITLE
Internalize type definitions

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/cypress-testing-library#145]
It would help with issues like #121 and in general I don't think there's a lot of value having them externalized to DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__cypress). Let's bring them in.

Anyone wanna work on this?

**Comment by TheGallery** [comment]
I am happy to pick this up.

**Comment by TheGallery** [comment]
This one is in progress. I am encountering some issues with conflicting type definitions but it's getting there.

**Comment by TheGallery** [comment]
I haven't been able to figure this out and I am kind of stuck now :-/ I am quoting my message on Discord about the issue

>  So, the precommit hook complains when running tsc because some jest and cypress type definitions are conflicting. I've looked into other similar PRs in testing-library packages but I couldn't find a solution. 

Is it worth opening a PR with what I have so far?

**Comment by kentcdodds** [comment]
Yes, please skip the hook if it's preventing you from opening your PR.
