### ISSUE TITLE
Normalizer access within Cypress

### ISSUE THREAD

**Issue by dwineknott** [testing-library/cypress-testing-library#147]
- `cypress-testing-library` version: 6.0.0
- `node` version: 12.16.3
- `npm` (or `yarn`) version: 6.14.4

Relevant code or config

```
 it('Manage Songwriters - Verify elements on page', () => {
        cy.visit('/songwriters/')
        cy.wait('@getWriters').then((xhr) => {
            const { objects } = xhr.responseBody as RootObject;
            }

        cy.get('.manage-writer-view > :nth-child(1) > #writer-list > li')
            .should('have.length', 10)
            .each(($writerList, index) => {
            const writer: Object  = objects[index]

       cy.wrap($writerList).within(() => {
                    cy.findAllByText(RegExp(writer.full_name, "i"),
                    {normalizer: getDefaultNormalizer({collapseWhitespace: true})} );
                
                    //iterate over each element within each `.songwriter`
               
                });
```

What you did:
Attempting to call `getDefaultNormalizer` from within the above script portion.  

What happened:

Getting from my IDE:

**Cannot find name 'getDefaultNormalizer'.**

Reproduction repository:
N/A

Problem description:
Is this Normalizer call available via the cypress-testing-library?  I don't see any documentation regarding this feature specific to Cypress.  I have read https://testing-library.com/docs/dom-testing-library/api-queries#normalization .  I'm hoping its a simple human error issue with the syntax I am using and this isn't a bug?  

Suggested solution:
 Extend access to this call within Cypress.

**Comment by kentcdodds** [comment]
Hello @dwineknott,

You'll have to import it directly from `@testing-library/dom`

```javascript
import {getDefaultNormalizer} from '@testing-library/dom'
```

I hope that helps!

**Comment by dwineknott** [comment]
Hi @kentcdodds .  Thank you!

This indeed resolved my initial issue, but I am now getting the following in the console when running my script.  In turn the new string is not being returned from here.  Any guidance you could provide would be much appreciated:


```
cy.findAllByText(RegExp(writer.full_name, "i"),
                        {normalizer: str => getDefaultNormalizer ({trim: true})(str).replace(/^\s+|\s+$|\s+(?=\s)/g,"")}
    
                    )
```

Error from console:

![Screen Shot 2020-08-13 at 5 16 57 PM](https://user-images.githubusercontent.com/11638121/90188377-5b492600-dd89-11ea-9988-0971bf7a5ba7.png)
