### ISSUE TITLE
Integrate which-query with Cypress

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/cypress-testing-library#150]
Feature request: integrate the Testing Library query picker into Cypress when `@testing-library/cypress` is installed

cc @bahmutov on the Cypress side

**Comment by benmonro** [comment]
@alexkrolick  interesting.  which-query is deployed to the chrome store so if Cypress can launch with extensions today would work fine.

Alternatively, the query suggestions that power which-query are part of the core now so you could also enable that via config.

**Comment by alexkrolick** [comment]
I think it would probably be a bit different UX, integrated into the Selector Playground

https://docs.cypress.io/guides/core-concepts/test-runner.html#Selector-Playground
https://docs.cypress.io/api/cypress-api/selector-playground-api.html#Syntax

There may need to be some modifications on the Cypress side to extend more than just `cy.get`, but also custom commands (e.g. `cy.findByRole`)

**Comment by benmonro** [comment]
Ah ok I see

**Comment by kentcdodds** [comment]
I'm not sure whether there's anything more that we'll be able to do with this here, so I'll close this.
