### ISSUE TITLE
Typings package has cypress as dependency with * version

### ISSUE THREAD

**Issue by lughino** [testing-library/cypress-testing-library#159]
- `cypress-testing-library` version: 7.0.1
- `@types/testing-library__cypress` version: 5.0.8
- `node` version: 12
- `npm` (or `yarn`) version: 1.22.5

What you did:

What happened:

Reproduction repository:

Problem description:

When I install the `@types/testing-library__cypress` typings, if I don't have the latest version of cypress installed, the cypress installation fails. (a well-known issue in cypress when more than one cypress version is installed)
This is due to having `cypress` with version `*` (latest) as a dependency of the typescript typings:
```json
{
    "private": true,
    "dependencies": {
        "@testing-library/dom": "^7.11.0",
        "cypress": "*"
    }
}
```

Suggested solution:

Remove those `dependencies` from the typing package and move them to `peerDependencies`/`devDependencies`

**Comment by kentcdodds** [comment]
Hi @lughino,

`@types/testing-library__cypress` is deprecated. Don't install it. The typings are built-in now.
