### ISSUE TITLE
Testing library causing test scripts failures 

### ISSUE THREAD

**Issue by Claudiu-BQA** [testing-library/cypress-testing-library#169]
- `cypress-testing-library` version:7.0.2
- `node` version:12.18.4
- `npm` (or `yarn`) version:6.14.6

What you did: I ran my testing scripts against a web application

**What happened:**

One error which was describing our different test failures was this one:

`SyntaxError: The following error originated from your test code, not from Cypress.`

I have also gotten this error while running this particular script:

```
describe('Canvas object validation A', () => {
    describe('Two accounts canvas validation', () => {
        it('User A writes to canvas', () => {
    });
    });
});
```

The challenge of this investigation was that this particular error was not linked to any specific test script. Therefore, I started investigating again the logs and came to the conclusion that the error occurs before executing the test script which failed upon the error in question. This fact made me to investigate one particular .js file where, besides others, we have an import of testing the testing library (`import '@testing-library/cypress/add-commands';`). I commented the file in question and the error didn't appear anymore. 

Next thing was to uncomment, one-by-one lines in that file. After further more testing, I came to the conclusion that specifically the testing library caused this error.

**Comment by Claudiu-BQA** [comment]
<!--
- `cypress-testing-library` version:7.0.2
- `node` version:12.18.4
- `npm` (or `yarn`) version:6.14.6

What you did: I ran my testing scripts against a web application

**What happened:**

One error which was describing our different test failures was this one:

`SyntaxError: The following error originated from your test code, not from Cypress.`

I have also gotten this error while running this particular script:

```
describe('Canvas object validation A', () => {
    describe('Two accounts canvas validation', () => {
        it('User A writes to canvas', () => {
    });
    });
});
```

The challenge of this investigation was that this particular error was not linked to any specific test script. Therefore, I started investigating again the logs and came to the conclusion that the error occurs before executing the test script which failed upon the error in question. This fact made me to investigate one particular .js file where, besides others, we have an import of testing the testing library (`import '@testing-library/cypress/add-commands';`). I commented the file in question and the error didn't appear anymore. 

Next thing was to uncomment, one-by-one lines in that file. After further more testing, I came to the conclusion that specifically the testing library caused this error.

--!>

**Comment by nickmccurdy** [comment]
What is the error? Can you please show the full output?

**Comment by Claudiu-BQA** [comment]
> What is the error? Can you please show the full output?

Hi, Nick! Here it is:
`  1) An uncaught error was detected outside of a test:
[0]      SyntaxError: The following error originated from your test code, not from Cypress.
[0] 
[0]   > Unexpected end of input
[0] 
[0] When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
[0] 
[0] Cypress could not associate this error to any specific test.
[0] 
[0] We dynamically generated a new test to display this failure.
[0]       at eval (<anonymous>)
`

**Comment by Claudiu-BQA** [comment]
> What is the error? Can you please show the full output?

The common state for the errors is : `SyntaxError: The following error originated from your test code, not from Cypress.`

**Comment by nickmccurdy** [comment]
This sounds like it could be an issue with Cypress settings on JSX code. Can you please post a repository or zip file that reproduces the issue?

**Comment by Claudiu-BQA** [comment]
> This sounds like it could be an issue with Cypress settings on JSX code. Can you please post a repository or zip file that reproduces the issue?

I have sent you an email that contains the zip which reproduces the issue along with some instructions.

**Comment by Claudiu-BQA** [comment]
> This sounds like it could be an issue with Cypress settings on JSX code. Can you please post a repository or zip file that reproduces the issue?

Any luck with the investigation?

**Comment by Claudiu-BQA** [comment]
> This sounds like it could be an issue with Cypress settings on JSX code. Can you please post a repository or zip file that reproduces the issue?

Hello, any progress on this issue? Could you suggest us any kind of approach to get past this flakyness?

**Comment by nickmccurdy** [comment]
Sorry for the delay, but based on the video you sent me this seems to be an unrelated issue with Cypress' test runner. If you're still having issues I'd recommend upgrading Cypress, and if that doesn't help reaching out to Cypress via support channels or GitHub.
