### ISSUE TITLE
Cypress is on 7.2.0, this library is pegged to "^6" - can that be updated

### ISSUE THREAD

**Issue by Pomax** [testing-library/cypress-testing-library#185]
- `cypress-testing-library` version: x
- `node` version: 16
- `npm` (or `yarn`) version: 7

What you did:

I tried to install `@testing-library/cypress`

What happened:

Can't: Cypress is now on 7.2.0 but this package still needs v6

Reproduction repository:

- install cypress
- try to install @testing-library/cypress

Suggested solution:

at the very least, update package.json to peg cypress to ^7 and then do a major version release (as compat with v7 is almost certainly going to break some folk's v6 settings)

**Comment by MichaelDeBoey** [comment]
Closed by #182
