### ISSUE TITLE
Feature Request: Cypress mount is chainable but not with testing-library

### ISSUE THREAD

**Issue by reintroducing** [testing-library/cypress-testing-library#187]
- `cypress-testing-library` version: 7.0.6
- `node` version: 12.13.0
- `npm` (or `yarn`) version: 6.12.0

Relevant code or config

```javascript
mount(
    <Button data-testid="test-id">
        Button
    </Button>
).findByTestId('test-id');
```

What you did:
Cypress v7 introduced the `mount` method for component testing. Mount is chainable and you can run cypress commands against it, like the following, for example:
```javascript
mount(<Button onClick={onClick}>Button onClick</Button>)
    .get('.Button-root')
    .click()
    .get('@onClick')
    .should('be.called');
```

What happened:
I tried to apply this concept to a test using Cypress Testing Library with the aforementioned code and it failed in finding the testid. The following, however, works:
```javascript
mount(
    <Button data-testid="test-id">
        Button
    </Button>
);

cy.findByTestId('test-id');
```

Reproduction repository:

Problem description: 
You cannot chain cypress testing library calls off of mount.

Suggested solution:
Add support for chaining off of mount to align with the rest of the Cypress API.

**Comment by reintroducing** [comment]
@NicholasBoll thank you for your suggestion, and I did just try it out, but unfortunately just adding the import statement into the support file breaks the tests:
```js
import {mount} from '@cypress/react';
```
results in
<img width="296" alt="Screen Shot 2021-05-11 at 9 21 10 AM" src="https://user-images.githubusercontent.com/259901/117850533-3e6b5180-b23a-11eb-84ce-13baf927c1f7.png">

**Comment by NicholasBoll** [comment]
I agree. If Cypress Testing Library was a React-specific Cypress plugin, I think it would make sense to add a `cy.mount`. But Cypress and Cypress Testing Library do not require React. This is probably why Cypress didn't add a `cy.mount` command and instead require you to import `mount` and use it.
