### ISSUE TITLE
Feature request - specify attribute for findByTestId or surface findByAttribute

### ISSUE THREAD

**Issue by penx** [testing-library/cypress-testing-library#192]
I'd like to use `data-test-id` rather than `data-testid` for `findByTestId`, but I don't think that's currently possible with cypress-testing-library.

Can the attribute be configurable in findByTestId, or can findByAttribute be surfaced?

**Comment by leschdom** [comment]
It should be possible (haven't tried it myself though):
https://github.com/testing-library/cypress-testing-library#config-testidattribute

**Comment by penx** [comment]
oops sorry, I had searched but clearly not hard enough 😀
