### ISSUE TITLE
Support Cypress version 9.0.0

### ISSUE THREAD

**Issue by exalted** [testing-library/cypress-testing-library#208]
- `cypress-testing-library` version: `8.0.1`
- `node` version: `v12.18.1`
- `npm` (or `yarn`) version: `npm@7.11.2`

**Relevant code or config**

N/A

**What you did:**

```
npm i --save-dev cypress@9.0.0
```

**What happened:**

N/A

**Problem description:**

Well, with the current peer dep definition, `npm` will keep complaining about not being able to resolve the dependency.

**Suggested solution:**

We should bump up the peer dev version.

**Comment by charklewis** [comment]
I have come across this issue too.

**Comment by HonkingGoose** [comment]
This can probably be closed now that PR #207 is merged. It will take some time for this to get released I think?
