### ISSUE TITLE
Testing library command timeouts doesn't register with the timeout-bar in the Cypress test-runner

### ISSUE THREAD

**Issue by Svish** [testing-library/cypress-testing-library#217]
- `cypress-testing-library` version: 8.0.2
- `node` version: 14.17.0
- `npm` (or `yarn`) version: 6.14.13

**What you did:**

Added a timeout to `findByRole`, like this:
```javascript
    cy.findByRole('button', {
      name: 'Not existing',
      timeout: 120_000,
    }).click();
```

**What happened:**

The timeout-bar of running/waiting testing-library commands in the Cypress test-runner finishes _way_ before 120 seconds are up. Looks to take around 10 seconds for it to finish? This is the progress-bar I'm talking about:

![image](https://user-images.githubusercontent.com/142162/158582495-92d204cb-6a31-4432-bfcc-456c1ccdbd8f.png)

If I use `timeout` on regular cypress commands, like `cy.get('foobar', { timeout: 120_000 })`, then the timeout-bar works correctly and does take 120 seconds to pass.

**Problem description:**

The timeout-option of testing-library commands doesn't seem to register correctly with the timeout-bar in the Cypress test-runner, like other commands do.

**Suggested solution:**

Timeout option on testing-library commands, should work and display the same as for other commands in the Cypress test-runner.

**Comment by JavierMartinz** [comment]
Any workaround for this? I'm also experiencing this issue.
