### ISSUE TITLE
cypress cannot find the line number of failed .findBy commands

### ISSUE THREAD

**Issue by rmmanseau** [testing-library/cypress-testing-library#232]
first, to address this:
```
HI! PLEASE STOP TO READ THIS!! If your issue is regarding one of the query
APIs (`getByText`, `getByLabelText`, etc), then please file it on the
https://github.com/kentcdodds/dom-testing-library repository instead. If you
file it here it will be closed. Thanks :)
```

the getBy functions do work properly, but when they fail cypress is not able to figure out where the failure is coming from & point to it accurately. This makes for difficult debugging because it's not possible to immediately jump to the failed testing library commands. I believe that this issue does belong here, as the issue is specific to integration with cypress test runner.

- `cypress-testing-library` version: 8.0.3
- `cypress` version: 10.10.0
- `node` version: 14.20
- `npm` (or `yarn`) version: 1.22.19

Relevant code or config

```javascript
describe('does not show failing assertion', () => {
  it('cy.findByText', () => {
    cy.mount(<App/>);
    cy.findByText(TEXT); // <---- cypress cannot tell that this line is the point of failure
  })

  it('cy.findByTestId', () => {
    cy.mount(<App/>);
    cy.findByTestId("code");
    cy.findByTestId("yeet"); // <---- cypress cannot tell that this line is the point of failure 
  })
})
```

What you did:

run a test that fails on a cy.findBy* command

What happened:

it creates a `TestingLibraryElementError` and dumps the entire state of the DOM

<img width="714" alt="image" src="https://user-images.githubusercontent.com/8755838/195952638-a4255f0d-b381-42b1-99da-bc4ad209d7f4.png">

What I expected:

it generates an `Assertion Error` and points to the line of the failing assertion.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/8755838/195952665-a33dc5db-767d-4e8b-903f-2c0a6c689d1e.png">

Reproduction repository: https://github.com/rmmanseau/cy-testing-library-repro

Problem description:

@testing-library/cypress doesn't generate the correct assertion type / stack trace / whatever is required by cypress in order for it to point to the location of the failing line.

Suggested solution:

do the thing that cypress expects.

**Comment by NicholasBoll** [comment]
I can look into this. This plugin takes the error created by DOM Testing Library to give more context to the error, but the stack trace isn't useful. Perhaps we can merge the message from DOM Testing Library and leave the rest of the assertion error alone.

**Comment by NicholasBoll** [comment]
If I replace the error message instead of the whole error, I can get what you want:

<img width="448" alt="error message" src="https://user-images.githubusercontent.com/338257/202004053-afe225dd-8c3c-412d-8696-70f7b1cc8127.png">

The top portion is the DOM Testing Library message while the Cypress error maintains Cypress context and stack traces.
