### ISSUE TITLE
feature request: integrate with interactive selector playground

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/cypress-testing-library#24]
- Cypress 3.1.2
- cypress-testing-library 2.3.3

It looks like it may be possible to hook into the Selector Playground to override the default selector generation. This would be good because the default returns very brittle selectors like `.table > nth-child(12) > a`.

https://docs.cypress.io/api/cypress-api/selector-playground-api.html#Syntax

**Comment by kentcdodds** [comment]
That sounds amazing!

**Comment by alexkrolick** [comment]
It looks like the `get`/`contains` methods are hardcoded in an array. If they could expose a hook to edit the list of methods, we'd be set.

 https://github.com/cypress-io/cypress/blob/2333d04a54acfd2d89d9d53cc60a49d46228ceef/packages/runner/src/selector-playground/selector-playground-model.js#L3

**Comment by kentcdodds** [comment]
Since there's nothing actionable we can do in this repo, I'll close this in favor of https://github.com/cypress-io/cypress/issues/2808
