### ISSUE TITLE
get/query variants don't exist

### ISSUE THREAD

**Issue by jamesarosen** [testing-library/cypress-testing-library#250]
The issue template says that questions about query APIs should go to https://github.com/kentcdodds/dom-testing-library, but these methods do exist there: https://github.com/testing-library/dom-testing-library/blob/0ce0c7054dfa64d1cd65053790246aed151bda9d/types/queries.d.ts#L297-L302

The [Cypress Testing Library docs](https://testing-library.com/docs/cypress-testing-library/intro) say

> You can now use all of DOM Testing Library's findBy, findAllBy, queryBy and queryAllBy commands off the global cy object.

Those same docs reference ["all library definitions"](https://github.com/testing-library/cypress-testing-library/blob/main/types/index.d.ts). That file includes only `findBy…` and `findAllBy…` methods. `cy.queryAllByTestId`, for example, doesn't exist.

- `cypress-testing-library` version: 8.0.3
- `node` version: v16.17.1
- `npm` (or `yarn`) version: 8.15.0

### Why I care

I want to look for `[data-testid="foo"]` -- which may or may not exist -- then make a decision based on what I get back. I want to wait for the standard timeout to make sure the element doesn't exist, so I don't want to just use `document.querySelector`.

**Comment by jamesarosen** [comment]
I think this is expected behavior given the README:

> query* queries are not supported. You should use the should('not.exist') assertion instead to check for the absence of an element.

> get* queries are not supported. find* queries do not use the Promise API of DOM Testing Library, but instead forward to the get* queries and use Cypress' built-in retryability using error messages from get* APIs to forward as error messages if a query fails.

I think this is an issue with the [Cypress Testing Library docs](https://testing-library.com/docs/cypress-testing-library/intro).

**Comment by vadimshvetsov** [comment]
Lost some time to realising this as well, opened pull request for that:
https://github.com/testing-library/testing-library-docs/pull/1344

**Comment by MatanBobi** [comment]
Thanks to @vadimshvetsov this is now properly documented.
I'm closing this one as it was a documentation issue, these queries aren't meant to be supported.
