### ISSUE TITLE
getBy* with .should('not.exist')

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/cypress-testing-library#30]
The behavior of cypress-testing-library's `getBy` queries is a bit different than the cypress built-in .get() method: the built-in will retry `should('not.exist')` until it times out, but the `getBy` queries timeout on the query. One workaround is to change to `getBy` to `queryBy`, but this requires a little bit of extra dom-testing-library knowledge that can confuse people coming from Cypress, and still doesn't retry.

**Alternative**

```js
// This doesn't work
cy.getByTestId('my-item').should('not.exist');

// This works for verifying an element isn't present *right now*
cy.queryByTestId('my-item').should('be.null');

// This should retry but does not
cy.queryByTestId('my-item').should('not.exist');
```

**Idea**

It might make sense for `queryBy*` to actually be aliased to `getBy*` in the cypress context?

EDIT: actually the .should() chain should really trigger a retry of the parent command. Maybe custom commands don't hook into .should correctly?

Related to #23, https://github.com/cypress-io/cypress/issues/3109

**Comment by kentcdodds** [comment]
Hmmm... [this test](https://github.com/kentcdodds/jest-cypress-react-babel-webpack/blob/2714f2694e9a03e636ae2aa91c8870a63506a9b1/cypress/e2e/calculator.js#L25-L26) as an assertion that an element does not exist and it works (even without the timeout argument. The timeout arg is there because otherwise Cypress will wait a full 4 seconds to make sure the element doesn't appear).

Am I missing something? Probably...

**Comment by alexkrolick** [comment]
it works if the query passes immediately, but not if it is present and disappears

**Comment by kentcdodds** [comment]
Oh right, that makes sense. A workaround would be to `wait` but that's a terrible workaround. Ok, so there are changes that need to happen in Cypress to allow us to do this then?

**Comment by alexkrolick** [comment]
I'm thinking Cypress should support hooking into the retry mechanism for custom commands. Filed an issue to discuss: https://github.com/cypress-io/cypress/issues/3109

**Comment by kentcdodds** [comment]
Super, thanks!

**Comment by alexkrolick** [comment]
It might be theoretically possible to emulate the `get` behavior more closely by copying some of the implementation from here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/querying.coffee, assuming this `Commands.addAll` method is accessible

**Comment by kentcdodds** [comment]
I'd be fine if anyone wants to try to make that happen. Then we can switch over to a built-in API when it becomes available.
