### ISSUE TITLE
Make default selectors more like cypress/jQuery

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/cypress-testing-library#33]
https://github.com/kentcdodds/dom-testing-library/issues/202#issuecomment-460354490

**Comment by helixbass** [comment]
-1 if the suggestion is to make `.getBy*()` not throw errors on missing elements

Keeping semantic compatibility with `react-testing-library` would seem like a high priority (for developers using both), and I know I'm writing tests that "implicitly assert" by just calling eg `.getByText()`

And why wouldn't it be ok to just use `.queryBy*()` for potentially missing elements (like `react-testing-library`)?

**Comment by alexkrolick** [comment]
Cypress already implicitly asserts `get`.

For background on why compatibility is desirable see #13, #31, #30, #24
