### ISSUE TITLE
Incorrect TypeScript return types from commands

### ISSUE THREAD

**Issue by simenbrekken** [testing-library/cypress-testing-library#39]
- `cypress-testing-library` version: 2.4.0
- `node` version: 10.15.3
- `npm` (or `yarn`) version: 6.4.1

**Relevant code or config**

```typescript
cy.getByTestId('activation-url').should(element => {
  expect(element.tagName).not.to.equal(undefined);
});
```

**What you did:**

According to https://github.com/kentcdodds/cypress-testing-library/blob/master/typings/index.d.ts#L70-L73 `element` should be a regular `HTMLElement` if no other type is provided.

**What happened:**

The test fails because `element` is a JQuery object and not an `HTMLElement`.

**Problem description:**

The return type of `getByPlaceholderText ` should be `Chainable<JQuery<E>>` as per https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts#L724

**Suggested solution:**

Update TypeScript typings to correctly match actual return values.

**Comment by simenbrekken** [comment]
It should also be noted that https://github.com/kentcdodds/cypress-testing-library/blob/master/tests/typescript-types/test.spec.ts is never run using Cypress or Jest meaning its tests would not pass if actually run.

**Comment by kentcdodds** [comment]
Do you mind contributing a fix?

**Comment by simenbrekken** [comment]
@kentcdodds I've got a local branch where I've started fixing types and that runs (failing) tests. Just wanted to get this reported in case I missed something.

**Comment by aaronmcadam** [comment]
I've just noticed this today. Did you get anywhere with a fix @simenbrekken?
