### ISSUE TITLE
(TS) Type SelectorMatcherOptions is missing timeout

### ISSUE THREAD

**Issue by ShimiTheFirst** [testing-library/cypress-testing-library#43]
- `cypress-testing-library` version: 3.0.1
- `node` version: 10.13.0
- `yarn` version: 1.13.0

**Relevant code or config**

```
cy.queryByText("foo", { timeout: 100 })
```

**What you did:**
Tried to change the value of the timeout option on `queryByText`.

**What happened:**
The test correctly waited for the set amount of time (100ms) but TS validation reports an error:
![ctl-type-err](https://user-images.githubusercontent.com/25421369/58622991-37f1a280-82cd-11e9-82a9-d58ae35c29b8.png)

**Problem description:**
Queries using the `SelectorMatcherOptions` type are missing the type definition for the timeout option.

**Suggested solution:**
If this is not intentional, take the same approach as for `MatcherOptions` in #28 – update `typings/index.d.ts`.

How it is now:
```
import {
  SelectorMatcherOptions,
  Matcher,
  MatcherOptions as DTLMatcherOptions,
  getByTestId,
} from 'dom-testing-library'

export interface CTLMatcherOptions {
  timeout?: number
}

export type MatcherOptions = DTLMatcherOptions | CTLMatcherOptions
```

How it could be:
<pre><code>
import {
  SelectorMatcherOptions <b>as DTLSelectorMatcherOptions</b>,
  Matcher,
  MatcherOptions as DTLMatcherOptions,
  getByTestId,
} from 'dom-testing-library'

export interface CTLMatcherOptions {
  timeout?: number
}

export type MatcherOptions = DTLMatcherOptions | CTLMatcherOptions
<b>export type SelectorMatcherOptions = DTLSelectorMatcherOptions | CTLMatcherOptions</b>
</code></pre>

**Comment by kentcdodds** [comment]
Thanks for this. Could you make a pull request for this?

**Comment by ShimiTheFirst** [comment]
I could try. It would be my very first PR though. I'll try to follow your course on egghead and contributing guide and see how far can I make it 🙂.

**Comment by kentcdodds** [comment]
Please note that I'm not currently using the TypeScript types in any project so I'll need another reviewer to review/merge these changes. Thanks!

**Comment by ppi-buck** [comment]
@ShimiTheFirst your solution looks fine to me. Just did just that locally and it works. 

For a simple change like this I would simply use the GitHub web frontend to create a PR. In fact I did just that https://github.com/testing-library/cypress-testing-library/pull/48

**Comment by kentcdodds** [comment]
@all-contributes please add @ShimiTheFirst for bugs

**Comment by kentcdodds** [comment]
@all-contributors please add @ShimiTheFirst for bugs

**Comment by kentcdodds** [comment]
Thanks to both of you for this!
