### ISSUE TITLE
Move typings to DefinitelyTyped

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/cypress-testing-library#68]
Several of the Testing Library repositories are doing this in an effort to improve the type definitions (it's recommended by the TypeScript team to do this if the source isn't written with TypeScript).

Anyone wanna take that on? Can reference this PR: https://github.com/testing-library/react-testing-library/pull/437

**Comment by simjes** [comment]
I'd like to work on this

**Comment by kentcdodds** [comment]
That would be fantastic! Please do!

**Comment by simjes** [comment]
Waiting for feedback for PR at DefinitelyTyped, will continue this when it's merged

**Comment by YOU54F** [comment]
Good work on this team,

Using semver, this release probably shouldn't have been a bug fix, as it breaks for users who consume the typings from this project and use carets in their package.json. I would have expected it to be a minor version release.
