### ISSUE TITLE
Types in DefinitelyTyped are missing v5 find* API 

### ISSUE THREAD

**Issue by jrnail23** [testing-library/cypress-testing-library#84]
- `cypress-testing-library` version:
- `node` version:
- `npm` (or `yarn`) version:

Relevant code or config

```javascript
```

What you did:

What happened:

Reproduction repository:

Problem description:

Suggested solution:

**Comment by bastibuck** [comment]
Were all ***getBy\**** methods directly replaced with ***findBy\****? should be pretty straight forward in this case to update the type definitions at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__cypress

**Comment by bastibuck** [comment]
I've created a PR over at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38368
Need to wait for the merge to happen and then update.

**Comment by bastibuck** [comment]
Should be resolved by now as the PR got approved and merged

Can be closed.
