### ISSUE TITLE
All(?) timeouts report as "cy.then() timed out after waiting '4000ms'" rather than printing actual expectation failure

### ISSUE THREAD

**Issue by jagregory** [testing-library/cypress-testing-library#89]
- `cypress-testing-library` version: 5.0.1
- `node` version: 12.6.0
- `npm` (or `yarn`) version: 1.17.3

Since upgrading to 5.0.1, it seems any timeouts are all being reported as `Your callback function returned a promise which never resolved`.

Any expectation that times out now just prints out the below, which obviously makes it pretty difficult to know which assertion it's actually failing on.

```
     CypressError: cy.then() timed out after waiting '4000ms'.

Your callback function returned a promise which never resolved.

The callback function was:

thenArgs => {
        const getValue = () => {
          const value = commandImpl(thenArgs.document);
          const result = Cypress.$(value); // Overriding the selector of the jquery object because it's displayed in the long message of .should('exist') failure message
          // Hopefully it makes it clearer, because I find the normal response of "Expected to find element '', but never found it" confusing

          result.selector = `${queryName}(${queryArgument(args)})`;

          if (result.length > 0) {
            consoleProps.yielded = result.toArray();
          }

          return result;
        };

        const resolveValue = () => {
          // retry calling "getValue" until following assertions pass or this command times out
          return Cypress.Promise.try(getValue).then(value => {
            return cy.verifyUpcomingAssertions(value, waitOptions, {
              onRetry: resolveValue
            });
          });
        };

        if (queryRegex.test(queryName)) {
          // For get* queries, do not retry
          return getValue();
        }

        return resolveValue().then(subject => {
          // Remove the error that occurred because it is irrelevant now
          if (consoleProps.error) {
            delete consoleProps.error;
          }

          return subject;
        });
      }
 ```

**Comment by jagregory** [comment]
Interestingly, all the failures also report that they timed out after waiting only 4000ms despite my tests specifying custom timeouts for them all.

<img width="322" alt="Screen Shot 2019-09-28 at 2 45 45 pm" src="https://user-images.githubusercontent.com/10828/65811617-c126d080-e1fe-11e9-9b22-9ca4b5b7ee47.png">
<img width="324" alt="Screen Shot 2019-09-28 at 2 45 39 pm" src="https://user-images.githubusercontent.com/10828/65811618-c1bf6700-e1fe-11e9-8212-7155c095c93c.png">
<img width="322" alt="Screen Shot 2019-09-28 at 2 45 32 pm" src="https://user-images.githubusercontent.com/10828/65811619-c1bf6700-e1fe-11e9-92ba-1110e798cd30.png">

Each one of those failed with a `CypressError: cy.then() timed out after waiting '4000ms'.` message.

**Comment by jagregory** [comment]
After a bit of digging, it looks like maybe https://github.com/testing-library/cypress-testing-library/commit/ab5263dcb36c8c299380af7ab424e759feccab0c introduced a bug.

Previously there was this code:

```js
.window({log: false})
.then({timeout: waitOptions.timeout + 100}, thenHandler)
```

but the `then` has been replaced and _doesn't_ retain the timeout option.

Tentative testing with the timeout re-added seems to have fixed the issue of timeouts not being respected (see: https://github.com/jagregory/cypress-testing-library/commit/d7fe43ec6f21ca8ca21fd989f837d5822c793238). I'm unsure whether this also fixes the incorrect failure messages (I assume that's what the `+ 100` is for)

**Comment by jagregory** [comment]
I can confirm that with the above mentioned change, if a legitimate timeout occurs I now get the expected message. For example: `CypressError: Timed out retrying: Expected to find element: '#option-1', but never found it.`

**Comment by Jmaharman** [comment]
We did have tests to check the timeouts were adhered to, I imagine a scenario was being missed.

@jagregory would you be able to add a test which shows the initial failure? It would be good to have a test in the suite to confirm this doesn't get broken again.
