### ISSUE TITLE
Can't click on one of multiple elements returned by findAll

### ISSUE THREAD

**Issue by FlopieUtd** [testing-library/cypress-testing-library#95]
- `Cypress Testing Library` version: 5.0.2
- `node` version: 12.0.0
- `yarn` version: 1.15.2

### Relevant code or config:

```js
cy.findAllByTestId("droppable").then(result => {
      // Convert to array because the result is a jQuery object, tried it as well without converting
      const resultArray = Array.from(result);
      resultArray[1].click({ force: true });
    });
```

### What you did:

My issue is that I can't click on a single element returned by findAllByTestId. In my console, I can see that the query resolves to 2 DOM elements. When clicking either the first or the second, I see that the findAllByTestId query is executed, but the click command is not. 

If I try clicking a nonexistent element from the array like resultArray[2], I do get an error that undefined cannot be clicked.

For context, the following does sort of work: 
 
```js
cy.findAllByTestId("droppable").click({multiple: true})
```

Using this snippet, I see that the first element was indeed clicked. As a result, both elements disappear and therefore I get an error that Cypress can't click the second. However, I don't want to click all elements, I want to click on just one of them.

### What happened:

All commands in my test are executed except the click command (32 is findAllBy, 33 should have been the click command but is the next command).

![image](https://user-images.githubusercontent.com/23555863/68656563-5cb39c80-0532-11ea-8d91-2cf095663cdf.png)

### Reproduction:

I tried reproducing but I couldn't get the Cypress suite to work in CodeSandbox.

### Problem description:

See above.

### Suggested solution:

I might be overlooking something but I don't find the docs very helpful at the moment: it lists one example of the combination of findAll with a user event, which I don't even think is valid code:

```cy.findAllByText('Jackie Chan').click()```

click() should in this case probably be click({multiple: true}) but an example showcasing my issue would be even more helpful I believe.

Thanks in advance! Hope I posted in the right place because I believe this has to do with the Cypress implementation and not with the findAll API.

**Comment by kentcdodds** [comment]
So to be clear, what you're saying is that we need to update our docs: `cy.findAllByText('Jackie Chan').click({multiple: true})`? Or is there more to this issue that I'm missing?

**Comment by FlopieUtd** [comment]
Hi Kent! No, that's not the issue. The issue is that I can't (or don't know how to) fire a user event on one out of multiple elements returned by findAllBy*. Like I said, ```cy.findAllByText('Jackie Chan').click()``` is invalid code so the docs should indeed be updated, but I believe it should be replaced with an example that clicks on a single element returned by findAllBy*, since it's not clear from the documentation how to do that.

**Comment by kentcdodds** [comment]
And `click({multiple: true})` doesn't work for you because when the first one is clicked the second one disappears? That sounds like something your application is doing. Do you *want* to click on both of them or you only want to click on the first one?

It sounds like your test could probably be rewritten so you don't have to use the `All` variant of the query and can just get the single element you want to click.

**Comment by VasilyShelkov** [comment]
If for some reason you do not want to go with the solution by @kentcdodds and you are still keen on using the `All` variant is to use Cypress' [`cy.spread`](https://docs.cypress.io/api/commands/spread.html#Syntax) which then allows you to click on one of the elements found. e.g.
```
cy.findAllByText('Jackie Chan').spread((firstButton, secondButton) => {
    secondButton.click()
})
```
There are probably other ways to do this, I think a good way to think about `findAllBy*` queries, is what you would do in Cypress if you used `cy.get` and it [returned an array](https://docs.cypress.io/api/commands/get.html#Find-5-elements-with-the-given-data-attribute). You could use the other operators like [`cy.each`](https://docs.cypress.io/api/commands/each.html#Syntax) and [`cy.first`](https://docs.cypress.io/api/commands/first.html#Syntax), although I haven't tested these and only used `cy.spread` myself

**Comment by FlopieUtd** [comment]
@kentcdodds There are definitely use cases in which you would want to click on one result returned by findAllBy*. In my case I have a rich text editor in which I want to add a text field, but I can insert it in 2 different places (droppables): above or under the current text field. Since there are 2 droppables, I can't use findBy* and must use findAllBy*.

@VasilyShelkov Thanks for your reply! Weird thing is, using .last() and .first() work perfectly as expected, but the spread callback as you described fails in the exact same way as my original snippet: the click event in the callback simply does not fire and the test goes to the next command. Logging both elements in the callback returns both elements just fine, but I can't click them.

For my specific needs, I can live with using .last() and .first(), but this does seem to be a bug in either Cypress or Cypress Testing Library.

**Comment by kentcdodds** [comment]
Could you use `within` to scope your query

**Comment by mbaranovski** [comment]
@FlopieUtd Habe you tried it with `.eq(nthItem)`?

Ref. https://docs.cypress.io/api/commands/eq.html#Syntax

**Comment by FlopieUtd** [comment]
@mbaranovski thank you so much, that is exactly the solution I was looking for. I'll submit a PR for updating the docs.
