### ISSUE TITLE
Add section in README on how to activate intellisense for library

### ISSUE THREAD

**Issue by kylemh** [testing-library/cypress-testing-library#97]
Not a bug, so I didn't follow the issue template! This is a feature request.

I'd like for intellisense to exist off of the `cy` object with the methods from `@testing-library/dom`. How do I do this? Is it possible?

**Comment by NicholasBoll** [comment]
Great suggestion! Intellisense can be tricky for libraries that use globals/namespaces like Cypress. The experience ranges from everything working right out of the box to messing with the config in ways that are specific to your project.

I think the easiest way in a JavaScript project is to add the following to the top of each Cypress spec file:

```js
/// <reference types="@testing-library/cypress" />
```

This is called a [Triple-Slash Directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) and it informs of external types to bring in. This should give intellisense to your files for this library.

The other way is to add a `cypress/jsconfig.json` file, but that adds Typescript checking in JavaScript files. You can set the `jsconfig.json` to be as loose as JavaScript and just get type definitions:

```json
{
  "compilerOptions": {
    "types": ["@testing-library/cypress"]
  }
}
```

The rest of the config will depend on your project.

**Comment by NicholasBoll** [comment]
If that works for you and you have time, could you create a pull request that updates the readme?

**Comment by kylemh** [comment]
I have a project coming up in a few weeks where I'll be starting a fresh set of Cypress tests. I'll make sure I hit this back up and add a PR!

**Comment by kylemh** [comment]
@NicholasBoll it doesn't look like `types` is a valid property of `compilerOptions` in `jsconfig.json`.

![Screen Shot 2020-04-14 at 1 27 27 PM](https://user-images.githubusercontent.com/9523719/79270843-b4449400-7e53-11ea-887f-7c0b535ad5fb.png)

**Comment by kylemh** [comment]
The triple slash directive isn't working for me either. I simply get a lint error (which I can obviously ignore), but no intellisense.

**Comment by kylemh** [comment]
Just found [this](https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Reference-type-declarations-via-jsconfig) 🤦‍♂️

I had a `exclude: ['node_modules']` which didnt seem to pair well with anything.

I've fixed intellisense for my project by removing exclude and just having `"include": ["node_modules/cypress", "./cypress/**/*.js"]` among my next to my compiler options.

I'll add a PR for documentation on this - should be simple!
